from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from io import BytesIO
from datetime import datetime

def generate_pdf_report(result_data: dict):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    elements.append(Paragraph("FairLens Bias Audit Report", styles['Title']))
    elements.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
    elements.append(Spacer(1, 20))

    # Section 1: Summary
    elements.append(Paragraph("1. Dataset Overview", styles['Heading2']))
    summary = result_data.get("dataset_summary", {})
    info = [
        ["Total Rows", str(summary.get("total_rows"))],
        ["Domain", result_data.get("domain", "N/A")],
        ["Outcome Column", summary.get("outcome_column", "N/A")],
        ["Status", result_data.get("compliance_status", "UNKNOWN")]
    ]
    t = Table(info, colWidths=[150, 300])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 20))

    # Section 2: Overall Score
    score = result_data.get("overall_bias_score", 0)
    severity = result_data.get("severity", "UNKNOWN")
    elements.append(Paragraph(f"Overall Bias Score: {score}/100 ({severity})", styles['Heading2']))
    elements.append(Paragraph(result_data.get("summary", ""), styles['Normal']))
    elements.append(Spacer(1, 20))

    # Section 3: Affected Groups
    elements.append(Paragraph("2. Detected Biases", styles['Heading2']))
    groups = result_data.get("affected_groups", [])
    if groups:
        group_data = [["Group", "Finding", "Severity"]]
        for g in groups:
            group_data.append([g['group'], g['plain_finding'], g['severity']])
        
        gt = Table(group_data, colWidths=[100, 250, 100])
        gt.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('PADDING', (0, 0), (-1, -1), 6),
        ]))
        elements.append(gt)
    else:
        elements.append(Paragraph("No significant bias detected in analyzed groups.", styles['Normal']))
    elements.append(Spacer(1, 20))

    # Section 4: Compliance & Risk
    elements.append(Paragraph("3. Compliance & Regulation Risk", styles['Heading2']))
    elements.append(Paragraph(f"<b>Regulation Risk:</b> {result_data.get('india_regulation_risk', 'N/A')}", styles['Normal']))
    elements.append(Paragraph(f"<b>Audit Note:</b> {result_data.get('audit_trail_note', 'N/A')}", styles['Normal']))
    elements.append(Spacer(1, 20))

    # Section 5: Recommended Fixes
    elements.append(Paragraph("4. Recommended Fixes", styles['Heading2']))
    fixes = result_data.get("fixes", [])
    for fix in fixes:
        elements.append(Paragraph(f"<b>{fix['title']}</b> (Priority: {fix['priority']})", styles['Normal']))
        elements.append(Paragraph(fix['description'], styles['Normal']))
        elements.append(Spacer(1, 10))

    # Disclaimer
    elements.append(Spacer(1, 40))
    elements.append(Paragraph("<i>Disclaimer: This report is generated by FairLens based on provided data. It should be used as a guide for internal compliance and does not constitute legal advice.</i>", styles['Italic']))

    doc.build(elements)
    pdf = buffer.getvalue()
    buffer.close()
    return pdf
